### ISSUE TITLE
windows no support??

### ISSUE THREAD

**Issue by LeePC** [rexlNico/LeagueOfMc#1]
[21:07:37 ERROR]: Error occurred while enabling LeagueOfMc v1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.RexlChrislai.Listeners.DamageBuildings.<init>(DamageBuildings.java:17) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_202]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_202]
        at com.RexlChrislai.Main.Main.loadListeners(Main.java:77) ~[?:?]
        at com.RexlChrislai.Main.Main.onEnable(Main.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getWorld(CraftServer.java:1042) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:517) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at com.RexlChrislai.Api.Factory.getConfigLocation(Factory.java:32) ~[?:?]
        at com.RexlChrislai.Gamestate.Ingame_STATE.<clinit>(Ingame_STATE.java:24) ~[?:?]
        ... 19 more

error.....

**Comment by rexlNico** [comment]
The project is not finished.
The project is no longer being developed.
